export const turnscopeIpcChannels = {
  getOverview: 'turnscope:get-overview',
  getToolHealth: 'turnscope:get-tool-health',
  getProject: 'turnscope:get-project',
  getSession: 'turnscope:get-session',
  getPatterns: 'turnscope:get-patterns',
  getDiagnostics: 'turnscope:get-diagnostics',
  getEvidence: 'turnscope:get-evidence',
  getImportStatus: 'turnscope:get-import-status',
  startImport: 'turnscope:start-import',
  cancelImport: 'turnscope:cancel-import',
  getImportedTheme: 'turnscope:get-imported-theme',
  importVsCodeTheme: 'turnscope:import-vscode-theme',
  searchOpenVsxThemes: 'turnscope:search-open-vsx-themes',
  importOpenVsxTheme: 'turnscope:import-open-vsx-theme',
  removeImportedTheme: 'turnscope:remove-imported-theme',
  updateCorrection: 'turnscope:update-correction',
  createCorrection: 'turnscope:create-correction',
  updateSignal: 'turnscope:update-signal',
} as const
